### ISSUE TITLE
Ability to generate specs for specific models

### ISSUE THREAD

**Issue by ram33** [strongloop/loopback-swagger#102]
Current loopback-component-explorer is good. But we have whole bunch of routes and dont want expose them all.

What we want is to expose routes only for specific models to our API’s users via different endpoints. Currently, there seems no option to generate spec for specific model via generateSwaggerSpec method. 

Is it feasible to do so? If not, are there any alternatives to achieve this?

**Comment by zbarbuto** [comment]
This functionality already exists. In your model-config do something like this (exposes only the `GET /` endpoint on your customer model):

```javascript
customer: {
  dataSource: 'ds',
  public: true,
  options: {
    remoting: { 
      sharedMethods: {
        '*': false,
        'find': true
      }
    }
  }
}
```

See here: https://github.com/strongloop/loopback/pull/3504

**Comment by ram33** [comment]
@zbarbuto Thank you for you response. But we have slightly different requirement than your example above. We need to expose all model routes, but different endpoint for each model. Letz say we have three models (customer, order and address). We would want to show routes for each model via different endpoint something like below.

domain.com/explorer/customer
domain.com/explorer/order

**Comment by zbarbuto** [comment]
Ah, my mistake. You mean mounting multiple explorers, one for each model 👌

**Comment by ram33** [comment]
yes, exactly
