### ISSUE TITLE
apic loopback:swagger not working with valid Swagger

### ISSUE THREAD

**Issue by waytoharish** [strongloop/loopback-swagger#111]
I am facing this issue when try to use apic loopback:swagger with valid Swagger file.

**Comment by raymondfeng** [comment]
Please post your swagger here.

**Comment by waytoharish** [comment]
Still not working after pulling fix

**Comment by waytoharish** [comment]
![error](https://user-images.githubusercontent.com/5119613/33122790-38cb72d2-cf9e-11e7-8677-cfd0a8ebc9c1.png)

**Comment by waytoharish** [comment]
[account-info-swagger.txt](https://github.com/strongloop/loopback-swagger/files/1495619/account-info-swagger.txt)

**Comment by raymondfeng** [comment]
I don’t think the fix will be picked up by apic automatically. Can you try the following?

```
npm i -g loopback-cli
cd your-project
lb swagger
```

**Comment by waytoharish** [comment]
C:\Users\HarishSharma\testmyswagger>lb swagger
? Enter the swagger spec url or file path: C:\Harish\DIP\APIFramework-master\APIFramework-master\Node\account-info-swagger.yaml
Loading C:\Harish\DIP\APIFramework-master\APIFramework-master\Node\account-info-swagger.yaml...
C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:91
    if (!definitions[tag]) {
                    ^

TypeError: Cannot read property 'SwaggerModel' of undefined
    at mapTag (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:91:21)
    at Array.forEach (native)
    at V2Generator.BaseGenerator.mapTagsToModels (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:123:15)
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:147:41
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:3096:16
    at eachOfArrayLike (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1055:9)
    at eachOf (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1103:5)
    at Object.eachLimit (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:3158:5)
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:146:13
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:121:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by dhmlau** [comment]
@waytoharish , could you please run the following command so that we know the LB related module versions? 
```
npm ls --depth
```

**Comment by raymondfeng** [comment]
Sorry the fix is not picked up by `loopback-cli` yet. See:

```
npm ls -g loopback-swagger
/Users/rfeng/.nvm/versions/node/v8.9.0/lib
└─┬ loopback-cli@4.0.0
  └─┬ generator-loopback@5.1.2
    ├─┬ loopback-api-definition@3.1.0
    │ └── loopback-swagger@4.3.0  deduped
    ├── loopback-swagger@4.3.0 
    └─┬ loopback-workspace@4.0.0
      └─┬ loopback-component-explorer@2.7.0
        └── loopback-swagger@2.9.0 
```

@dhmlau Can you upgrade to `loopback-swagger@^5.4.0` in `generator-loopback` and create new release of `generator-loopback`?

**Comment by dhmlau** [comment]
@raymondfeng , will do.

**Comment by dhmlau** [comment]
Fix is released:
`loopback-swagger@5.4.0`
`generator-loopback@5.2.0`

@waytoharish , could you please verify?

**Comment by waytoharish** [comment]
Done running LoopBack generator

Updating swagger and product definitions
Error: The LoopBack application is not loaded.
Cannot load the LoopBack application: Unexpected identifier
Please fix the problem and run `apic loopback:refresh`


C:\Users\HarishSharma\testloopback>lb swagger
? Enter the swagger spec url or file path: C:\Harish\DIP\account-info-swagger.yaml
Loading C:\Harish\DIP\account-info-swagger.yaml...
C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:91
    if (!definitions[tag]) {
                    ^

TypeError: Cannot read property 'SwaggerModel' of undefined
    at mapTag (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:91:21)
    at Array.forEach (native)
    at V2Generator.BaseGenerator.mapTagsToModels (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\loopback-swagger\lib\codegen\generator-base.js:123:15)
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:147:41
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:3096:16
    at eachOfArrayLike (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1055:9)
    at eachOf (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:1103:5)
    at Object.eachLimit (C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\async\dist\async.js:3158:5)
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:146:13
    at C:\nodejs\node_modules\npm\node_modules\loopback-cli\node_modules\generator-loopback\swagger\spec-loader.js:121:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

C:\Users\HarishSharma\testloopback>npm ls -g loopback-swagger
npm@3.10.10 C:\nodejs\node_modules\npm
`-- loopback-swagger@5.4.0  extraneous

npm ERR! extraneous: loopback-swagger@5.4.0 C:\nodejs\node_modules\npm\node_modules\loopback-swagger

**Comment by waytoharish** [comment]
C:\Users\HarishSharma\testloopback>npm ls -g generator-loopback
npm@3.10.10 C:\nodejs\node_modules\npm
`-- generator-loopback@5.2.0  extraneous

npm ERR! extraneous: generator-loopback@5.2.0 C:\nodejs\node_modules\npm\node_modules\generator-loopback

**Comment by dhmlau** [comment]
@waytoharish , please make sure you've reinstalled `loopback-cli`.  I've tried the following steps myself and it seems to work fine:

1. uninstall loopback-cli
`npm uninstall -g loopback-cli`
2. reinstall loopback-cli
`npm i -g loopback-cli`

3. Run `npm ls -g loopback-swagger`
The output should be something like:
```
...
└─┬ loopback-cli@4.0.0
  └─┬ generator-loopback@5.2.0
    ├─┬ loopback-api-definition@3.1.0
    │ └── loopback-swagger@4.3.0
    ├── loopback-swagger@5.4.0
    └─┬ loopback-workspace@4.0.0
      └─┬ loopback-component-explorer@2.7.0
        └── loopback-swagger@2.9.0
```

4. Run `lb swagger`

My output is:
```
? Enter the swagger spec url or file path: definitions/account-info-swagger.yaml
Loading definitions/account-info-swagger.yaml...
? Select models to be generated: (Press <space> to select, <a> to toggle all, <i> to inverse selection)createAccountRequest_body, createAccou
ntRequest_response_201, getAccountRequest_response_200, getAccounts_response_200, getAccount_response_200, getAccountTransactions_response_20
0, getAccountBeneficiaries_response_200, getAccountBalances_response_200, getAccountDirectDebits_response_200, getAccountStandingOrders_respo
nse_200, getAccountProduct_response_200, getStandingOrders_response_200, getDirectDebits_response_200, getBeneficiaries_response_200, getTran
sactions_response_200, getBalances_response_200, getProducts_response_200, SwaggerModel
? Select the datasource to attach models to: db (memory)
Creating model definition for createAccountRequest_body...
Creating model definition for createAccountRequest_response_201...
Creating model definition for getAccountRequest_response_200...
Creating model definition for getAccounts_response_200...
Creating model definition for getAccount_response_200...
Creating model definition for getAccountTransactions_response_200...
Creating model definition for getAccountBeneficiaries_response_200...
Creating model definition for getAccountBalances_response_200...
Creating model definition for getAccountDirectDebits_response_200...
Creating model definition for getAccountStandingOrders_response_200...
Creating model definition for getAccountProduct_response_200...
Creating model definition for getStandingOrders_response_200...
Creating model definition for getDirectDebits_response_200...
Creating model definition for getBeneficiaries_response_200...
Creating model definition for getTransactions_response_200...
Creating model definition for getBalances_response_200...
Creating model definition for getProducts_response_200...
Creating model definition for SwaggerModel...
Model definition created/updated for SwaggerModel.
Model definition created/updated for createAccountRequest_body.
Model definition created/updated for createAccountRequest_response_201.
Model definition created/updated for getAccountRequest_response_200.
Model definition created/updated for getAccount_response_200.
Model definition created/updated for getAccounts_response_200.
Model definition created/updated for getAccountTransactions_response_200.
Model definition created/updated for getAccountBeneficiaries_response_200.
Model definition created/updated for getAccountDirectDebits_response_200.
Model definition created/updated for getAccountStandingOrders_response_200.
Model definition created/updated for getAccountProduct_response_200.
Model definition created/updated for getDirectDebits_response_200.
Model definition created/updated for getBeneficiaries_response_200.
Model definition created/updated for getTransactions_response_200.
Model definition created/updated for getStandingOrders_response_200.
Model definition created/updated for getBalances_response_200.
Model definition created/updated for getAccountBalances_response_200.
Model definition created/updated for getProducts_response_200.
Creating model config for createAccountRequest_body...
Creating model config for createAccountRequest_response_201...
Creating model config for getAccountRequest_response_200...
Creating model config for getAccounts_response_200...
Creating model config for getAccount_response_200...
Creating model config for getAccountTransactions_response_200...
Creating model config for getAccountBeneficiaries_response_200...
Creating model config for getAccountBalances_response_200...
Creating model config for getAccountDirectDebits_response_200...
Creating model config for getAccountStandingOrders_response_200...
Creating model config for getAccountProduct_response_200...
Creating model config for getStandingOrders_response_200...
Creating model config for getDirectDebits_response_200...
Creating model config for getBeneficiaries_response_200...
Creating model config for getTransactions_response_200...
Creating model config for getBalances_response_200...
Creating model config for getProducts_response_200...
Creating model config for SwaggerModel...
Model config created for createAccountRequest_body.
Model config created for createAccountRequest_response_201.
Model config created for getAccountRequest_response_200.
Model config created for getAccounts_response_200.
Model config created for getAccount_response_200.
Model config created for getAccountTransactions_response_200.
Model config created for getAccountBeneficiaries_response_200.
Model config created for getAccountBalances_response_200.
Model config created for getAccountDirectDebits_response_200.
Model config created for getAccountStandingOrders_response_200.
Model config created for getAccountProduct_response_200.
Model config created for getStandingOrders_response_200.
Model config created for getDirectDebits_response_200.
Model config created for getBeneficiaries_response_200.
Model config created for getTransactions_response_200.
Model config created for getBalances_response_200.
Model config created for getProducts_response_200.
Model config created for SwaggerModel.
Generating /Users/xxxx/loopback-example/swagger-test/common/models/swagger-model.js
Models are successfully generated from swagger spec.
```

**Comment by waytoharish** [comment]
Hi ,
I have followed same step mentioned by you- and now getting -
C:\Users\HarishSharma\testloopback>npm ls -g loopback-swagger
npm@3.10.10 C:\nodejs\node_modules\npm
`-- loopback-swagger@5.4.0  extraneous

npm ERR! extraneous: loopback-swagger@5.4.0 C:\nodejs\node_modules\npm\node_modules\loopback-swagger

**Comment by dhmlau** [comment]
@waytoharish , were you able to run the `lb swagger` command? 
I'm seeing a different output as you.  I've also tried to install `loopback-swagger` globally, but didn't get the same error as you.  

```
/Users/dianalau/.nvm/versions/node/v6.11.0/lib
├─┬ apiconnect@2.7.62
│ ├─┬ apiconnect-cli-loopback@2.6.6
│ │ ├─┬ generator-loopback@2.3.0
│ │ │ ├─┬ loopback-api-definition@3.1.0
│ │ │ │ └── loopback-swagger@4.3.0 
│ │ │ └── loopback-swagger@3.0.2 
│ │ ├─┬ loopback-api-definition@1.1.1
│ │ │ └── loopback-swagger@2.9.0 
│ │ └─┬ loopback-workspace@3.40.1
│ │   └─┬ loopback-component-explorer@2.7.0
│ │     └── loopback-swagger@2.9.0 
│ └─┬ apiconnect-cli-pm@2.4.6
│   └─┬ microgateway@1.6.6
│     └── loopback-swagger@2.9.0  extraneous
└─┬ loopback-cli@4.0.0
  └─┬ generator-loopback@5.2.0
    ├─┬ loopback-api-definition@3.1.0
    │ └── loopback-swagger@4.3.0 
    ├── loopback-swagger@5.4.0 
    └─┬ loopback-workspace@4.0.0
      └─┬ loopback-component-explorer@2.7.0
        └── loopback-swagger@2.9.0 

npm ERR! extraneous: loopback-swagger@2.9.0 /Users/dianalau/.nvm/versions/node/v6.11.0/lib/node_modules/apiconnect/node_modules/microgateway/node_modules/loopback-swagger
```

@raymondfeng , do you think we need to update `microgateway` dependency too?

**Comment by waytoharish** [comment]
Hi,
I followed the step you had mentioned but no luck.

**Comment by dhmlau** [comment]
@raymondfeng , any ideas?  I could run the `lb swagger` command, although I got some error when doing `npm ls -g loopback-swagger`.

**Comment by dhmlau** [comment]
@waytoharish , if you run `lb swagger`, could you please show us the output?

**Comment by dhmlau** [comment]
Talked to @waytoharish.  It was working fine when using `lb swagger`, but not `apic loopback:swagger` command.

**Comment by dhmlau** [comment]
Talked to @waytoharish directly.  Closing this because it is not related to loopback modules but apiconnect node modules.
