### ISSUE TITLE
NSP Vulnerability Prototype Pollution

### ISSUE THREAD

**Issue by jeemok** [strongloop/loopback-swagger#120]
NSP has reported a Prototype Pollution security vulnerability for lodash library on all version below 4.17.5.

More info: https://nodesecurity.io/advisories/577

Currently loopback-swagger v3.x uses lodash v3.x. Is it possible to update the lodash to v4.x?

**Comment by dhmlau** [comment]
@jeemok, would you like to submit a PR against the `3.x` branch?

**Comment by bajtos** [comment]
I have published the fix from #121 as `loopback-swagger@3.0.3`.
