### ISSUE TITLE
Incorrect swagger.json generated for return values having a http.target set to header or status

### ISSUE THREAD

**Issue by yshing** [strongloop/loopback-swagger#130]
# Description/Steps to reproduce
Step to reproduce:
The example from loopback doc.
https://loopback.io/doc/en/lb3/Remote-methods.html#argument-descriptions
```js
module.exports = function(MyModel) {
  MyModel.download = function(cb) {
    // getTheStreamBody() can be implemented by calling http.request() or fs.readFile() for example
    getTheStreamBody(function(err, stream) {
      if (err) return cb(err);
      // stream can be any of: string, buffer, ReadableStream (e.g. http.IncomingMessage)
      cb(null, stream, 'application/octet-stream');
    });
  };

  MyModel.remoteMethod('download', {
    returns: [
      {arg: 'body', type: 'file', root: true},
      {arg: 'Content-Type', type: 'string', http: { target: 'header' }}
    ]
  });
};
```

# Cause in source code
Comparing the `convertReturnsToSwagger` function [source code](https://sourcegraph.com/github.com/strongloop/loopback-swagger/-/blob/lib/specgen/route-helper.js#L122-155) to `convertAcceptsToSwagger` function [source code](https://sourcegraph.com/github.com/strongloop/loopback-swagger/-/blob/lib/specgen/route-helper.js#L61-87)

The step of filtering out arguments pointing different http items is missing.

# Fix suggestion

Filter out the arguments having `http.target` set to `header|status` in the `convertReturnsToSwagger` function.

**Comment by dhmlau** [comment]
@hacksparrow , could you PTAL? thanks.
