### ISSUE TITLE
Fail gracefully when a model property definition is incomplete 

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-swagger#18]
I have reinstalled all node_modules, changed to loopback-component-explorer 2.1.1 and right after starting the app with node . it throws an error

```
project\node_modules\loopback-swagger\lib\specgen\schema-builder.js:149
    if (key in ldlDef) {
               ^

TypeError: Cannot use 'in' operator to search for 'min' in true
    at Object.exports.buildMetadata (project\node_modules\loopback-swagger\lib\specgen\schema-builder.js:149:16)
    at Object.exports.buildFromLoopBackType (project\node_modules\loopback-swagger\lib\specgen\schema-builder.js:62:24)
    at project\node_modules\loopback-swagger\lib\specgen\model-helper.js:57:34
    at Array.forEach (native)
    at Object.module.exports.registerModelDefinition (project\node_modules\loopback-swagger\lib\specgen\model-helper.js:49:29)
    at createSwaggerObject (project\node_modules\loopback-swagger\lib\specgen\swagger-spec-generator.js:54:17)
    at mountSwagger (project\node_modules\loopback-component-explorer\index.js:96:23)
    at routes (project\node_modules\loopback-component-explorer\index.js:46:3)
    at explorer (project\node_modules\loopback-component-explorer\index.js:26:46)
    at Object.mountLoopBackExplorer [as func] (project\server\boot\explorer.js:18:21)
```

**Comment by bajtos** [comment]
@barocsi thank you for the bug report. Could you please provide us with a small app that we can run to reproduce the issue locally on our machines? See [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) for more details.

**Comment by barocsi** [comment]
Willy try, meanwhile still trying to identify the root...since I have deleted node_modules directory and invoked npm install some other issues arise such as https://github.com/strongloop/loopback-datasource-juggler/issues/613#issuecomment-156140395

**Comment by barocsi** [comment]
It turned out after debugging loopback-sandbox\node_modules\loopback-swagger\lib\specgen\schema-builder.js that I had a missing type property from a model.json config file. Unfortunately I do not have implications whether It was caused by the complete reinstall of my node_modules and upgrade of certain modules, but the solution is working.

```json
  "properties": {
    "value": {
      "type": "number",
      "required": true
    },
    "questionIndex": {
      "type": {
        "type": "number /// this line was missing",
        "required": true
      }
    }
  },
```

**Comment by bajtos** [comment]
> I had a missing type property from a model.json config file

Thank you @barocsi for identifying the problem! I am reopening this issue, we should fail gracefully in when the property definition is incomplete and provide a helpful error message, ideally mentioning both model and property names.

**Comment by bajtos** [comment]
Alternatively, we can do the same as LoopBack runtime does. I'd expect the property is treated as if it has type `any`, but that need to be verified first.

**Comment by epaezrubio** [comment]
How about using `ldlDef[key]` or `ldlDef.hasOwnProperty(key)` to avoid the exception?

**Comment by 0candy** [comment]
@barocsi 
Is there a reason why type was nested?
>    "questionIndex": {
      "type": {
        "type": "number /// this line was missing",
        "required": true
      }

and not like this?
    "questionIndex": {
        "type": "number"
        "required": true
      }
