### ISSUE TITLE
Support for includes in Swagger model

### ISSUE THREAD

**Issue by kasperg** [strongloop/loopback-swagger#29]
I am working with a Loopback service with relations between the different models. We could use includes to optimize data retrieval but the Swagger specification for the models does not contain references to included models.

This becomes a problem when using tools like `swagger-api/swagger-codegen` to generate client libraries as these libraries cannot make use of the the includes.

It this something you have considered?

I am unsure whether this belongs here or `strongloop/loopback-component-explorer`. If this should be posted elsewhere let me know.

**Comment by richardpringle** [comment]
@kasperg I think this is the right place!

**Comment by dhmlau** [comment]
Reopening as there's a PR in progress.
