### ISSUE TITLE
swagger api between or from loopback remoting metadata

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback-swagger#3]
Utilities to transform between Swagger API specs and LoopBack remoting metadata.

The word "between" indicates a two way operation, or is it only from swagger to loopback.

I have to read the code to find out what is true, but a "between" use case is nice.

**Comment by OwenBrotherwood** [comment]
I have "discovered" that the raw output of the <site>/explorer is a swagger :: but version 1.2
I google a bit more to find out if it is possible to force version 2.0

**Comment by bajtos** [comment]
@OwenBrotherwood you are correct, loopback-swagger converts from Swagger to remoting metadata, while loopback-explorer provides Swagger metadata built from remoting metadata.

Swagger 2.0 support is tracked by this GH issue: https://github.com/strongloop/loopback-explorer/issues/54
