### ISSUE TITLE
Cannot figure out how to define inline models for custom API endpoints

### ISSUE THREAD

**Issue by peeter-tomberg** [strongloop/loopback-swagger#48]
Hello!

I'm trying to create a simple API endpoint that accepts 2 parameters, e.g:
POST /plan/compositeCreate
```
{
    plan: PlanModel,
    frequency: [FrequencyModel]
}
```

The closest I've gotten is: 
```
    Plan.remoteMethod('compositeCreate', {
        http: { verb: 'post' },
        accepts: [
            { arg: 'data', type: 'object', required: true, http: { source: 'body' } }
        ],
        returns: { type: Plan, root: true }
    });
```

The problem is, whenever I try to define an inline type, e.g. 
```
    { arg: 'data', type: { plan: {}, frequency: {} }, required: true, http: { source: 'body' } }
```
It wont register the inline model in swagger. Somehow it'll show the "Plans" definition in the data field.
When I try to register 2 body args, swagger wont POST them to the backend. What am I doing wrong?

**Comment by richardpringle** [comment]
@peeter-tomberg, the only supported types are the [LoopBack types](https://docs.strongloop.com/display/APIC/LoopBack+types). I've linked the documentation, please check that out. 

I'm closing this issue for now but if you feel that it is not solved, please re-open it and mention me in a new comment. Feel free to carry on any conversation in the closed issue as well.
