### ISSUE TITLE
accessToken included twice in curl commandline

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback-swagger#50]
For example, the curl line for a given "Paths" model is shown here with two entries of the accessToken, and usually this makes the server not behave properly (can get crashes where userId is referenced, etc...)

```
curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Paths?type=media&access_token=vw5AieDAruaigAHGCzdQquKzWK1GVGzvmsARNDLz0Q5hEas8DKoAISzkpYdU1dj4&access_token=vw5AieDAruaigAHGCzdQquKzWK1GVGzvmsARNDLz0Q5hEas8DKoAISzkpYdU1dj4"
```

**Comment by richardpringle** [comment]
Hey @azatoth, I saw this behavior in the `[loopback-component-explorer](https://github.com/strongloop/loopback-component-explorer)`. If I am not mistaken, the issue should go in that repo, correct?

**Comment by azatoth** [comment]
@richardpringle Oh, I thought I reported it to the right project :/ my bad

**Comment by richardpringle** [comment]
@azatoth, if you have done so already, please disregard this, but if not, could you please mention me in the new issue?

Cheers
