### ISSUE TITLE
schemes is `undefined`

### ISSUE THREAD

**Issue by pthieu** [strongloop/loopback-swagger#52]
1. Create a LB app via APIC CLI i.e. `apic loopback`
2. Require `loopback-swagger` and try to `generateSwaggerSpec` on the app:

```
var generateSwaggerSpec = require('loopback-swagger').generateSwaggerSpec;
var swaggerSpec = generateSwaggerSpec('path/to/app');
```

We get this result: https://gist.github.com/pthieu/d1d815b2cdb7c4a6327b4b4a08d06532

Check https://gist.github.com/pthieu/d1d815b2cdb7c4a6327b4b4a08d06532/6b65bbc92b4b0f2e3daa6d306a49ee2608d264f6 for `Revision 1`, looks like the file write omitted the `undefined` values.

**Comment by sam-github** [comment]
@bajtos we need scheme to be populated, because otherwise, tooling is forced to guess, and in the case of us pushing the loopback swagger to liberty, it always guesses HTTPS, because we push the swagger over HTTPS.

I suspect that this will need to interact with https://github.com/strongloop/loopback/issues/2182, because at the moment LoopBack wouldn't know if it is HTTP, HTTPS, or both. At a minimum, perhaps there can be at least a json field somewhere, defaulting to HTTP, that specifies the scheme. That is manual, and could be wrong, but at least it could be used to control the schemes in the swagger output.

**Comment by bajtos** [comment]
Quoting from http://swagger.io/specification/#swaggerObject
> The transfer protocol of the API. Values MUST be from the list: "http", "https", "ws", "wss". If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.

We are intentionally not specifying `schemes` field to trigger the part *the default scheme to be used is the one used to access the Swagger definition itself.*

This is based on the assumption that the swagger doc will be served by the same LoopBack app providing the API, i.e. at the same base url (scheme+host+port(.

Now I totally agree that it's a valid case to serve the application at a different base url that the swagger document. However, I don't think it's the responsibility of the LoopBack application to know where it will be deployed to and what will the base url. For example, when the app is running behind a reverse proxy (e.g. a Gateway), the base url for swagger consumers will be different from what the LoopBack application sees itself.

If the tool running `loopback-swagger` has access to the information about the scheme, host and port, then it can easily customize the swagger output:

```js
var swaggerSpec = generateSwaggerSpec(app, {
  protocol: 'http',
  host: 'api.example.com',
  // unfortunately "port" is not supported now
  basePath: '/my-api-v1',
});
``` 

An alternative is to add `swagger` section to application's `server/config.json` and provide `protocol` value there. I know, this is exact opposite of what I wrote earlier that LoopBack apps should not be responsible to know where they are going to be deployed.

```json
{
  "host": "localhost",
  "port": 3000,
  "restApiRoot": "/api",
  "swagger": {
    "protocol": "http",
    "host": "api.example.com",
    "basePath": "/my-api-v1",
  }
}
```

**Comment by bajtos** [comment]
FWIW, here is our current docs on setting up HTTPS: https://docs.strongloop.com/display/LB/Preparing+for+deployment#Preparingfordeployment-UsingSSL

**Comment by bajtos** [comment]
We need to update the docs (see comment above) and the HTTPS example app to add the following section to their `server/config.json`:

```json
{
  "swagger": {
    "protocol": "https",
  }
}
```

**Comment by sam-github** [comment]
@crandmck @superkhau see above ----^

**Comment by superkhau** [comment]
@sam-github PTAL https://github.com/strongloop/loopback-example-ssl/pull/14

**Comment by crandmck** [comment]
Updated https://docs.strongloop.com/display/APIC/Preparing+for+deployment#Preparingfordeployment-Configuretheapp

**Comment by bajtos** [comment]
Looks like this issue has been fixed, I am closing it now. Feel free to comment and/or reopen if you disagree.
