### ISSUE TITLE
StrongLoop API Explorer, do not show whole defition model in Data Type - Model Schema

### ISSUE THREAD

**Issue by Biax2099** [strongloop/loopback-swagger#62]
I have this model "Product.json":

```json
 {
  "name": "Product",
  "strict": "validate",
  "idInjection": false,
  "properties": {
    "Brand": [
      {
        "size": {
          "type": "Number"
        },
        "color" : {
          "type" : "String"
        }
      }
    ],
    "ProductId": {
      "type": "Number",
      "id": true,
      "required": true,
      "length": null,
      "precision": 10,
      "scale": 0
    },
    "Availability": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 10,
      "scale": 0
    }
  }
}
```

My remote method:

```javascript
Model.remoteMethod(
    'CreateProduct', {
      accepts: [
        { arg: 'context', type: 'object', 'http': function (ctx) { return ctx; } },
        { arg: 'data', type: 'Product', http: { source: 'body' } }
      ],
      http: { path: '/CreateProduct', verb: 'post' },
      returns: { arg: 'message', type: 'string', required: true, root: false }
    });
```

Why in StrongLoop API Explorer i see this?

[
![untitled](https://cloud.githubusercontent.com/assets/22635402/19109901/aeb5c458-8af7-11e6-9646-2850a2ca959b.png)
](url)

The property "Brand" its so defined...

"Brand": [
      {
        "size": {
          "type": "Number"
        },
        "color" : {
          "type" : "String"
        }
      }
    ]

**Comment by Biax2099** [comment]
Sorry, nobody of the admins can answer me? Thanks!

**Comment by gunjpan** [comment]
@Biax2099 : Hi, apologies for a delayed reply. In your following code:
```json
"Brand": [
      {
        "size": {
          "type": "Number"
        },
        "color" : {
          "type" : "String"
        }
      }
    ],
```

`Brand` property is defined as `Array of Objects` datatype, which would accept an array of objects, which is displayed correctly in `loopback-explorer`. 

I believe, you're trying to expose `Brand` property as an object where you can manipulate values for `size` & `color` and is generic across all instances of the Model, then, you should define 
`Brand` to have [type: `Object`](https://docs.strongloop.com/display/APIC/LoopBack+types#LoopBacktypes-Objecttypes), as follows:
```json
"Brand": {
      "type": {
        "size": {
          "type": "Number"
        },
        "color": {
          "type": "String"
        }
      }
    },
```

or 

```json
"Brand":
      {
        "type": {
        "size": "Number",
        "color" : "String"
        }
      },
```
Both flavors would work and display `Brand` as following:

![screen shot 2016-10-11 at 3 55 23 pm](https://cloud.githubusercontent.com/assets/14811089/19286325/39d61858-8fcb-11e6-80b2-66cda8e96197.png)

This should resolve your issue, closing for now.
Please let me know, if you need any further assistance, in the comments and I'll help you the best I can. Thank you :)

**Comment by Biax2099** [comment]
Hi @gunjpan, thank you so much for your answer! 

I can ask you if is possible to declare a prototype to function TypeRegistry in ..\node_modules\loopback-component-explorer\node_modules\loopback-swagger\lib\specgen\type-registry.js ?

**Comment by gunjpan** [comment]
@Biax2099 : Sorry, I didn't get your question. Could you please explain a bit more.

FYI: `specgen` adheres to Open API specification a.k.a. Swagger specification (read more about it [here](http://swagger.io/specification/)).

**Comment by Biax2099** [comment]
Hi @gunjpan, sorry i try to explaning better. If I would to record a custom json schema (not x-any, ObjectID, GeoPoint and Loopback Model) using `specgen`, how i can? Its possible?
Thanks!
