### ISSUE TITLE
Export authSchemes and securityDefinitions

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-swagger#65]
_From @JonnyBGod on May 10, 2016 20:6_

We should be able to export auth specifications with swagger spec.

At least make it easy to hardcode it in options.

_Copied from original issue: strongloop/loopback-component-explorer#162_

**Comment by superkhau** [comment]
_From @JonnyBGod on May 10, 2016 20:9_

It would be perfect if it was possible to easily integrate with loopback-component-oauth2

**Comment by superkhau** [comment]
_From @richardpringle on August 11, 2016 19:1_

@JonnyBGod, should this be in [loopback-swagger/issues](https://github.com/strongloop/loopback-swagger/issues)?

**Comment by superkhau** [comment]
_From @gunjpan on October 11, 2016 20:10_

@JonnyBGod : Could you please post this issue in the correct place as shown above?
Also, a sample/example to understand what you're proposing will definitely help within the description.
Closing this now. Thank you and have a great day!

**Comment by superkhau** [comment]
@JonnyBGod I'm going to help move this issue over to the repo mentioned by @gunjpan and @richardpringle. Please add a better description of your issue there. I'll add a template you can edit there.

**Comment by superkhau** [comment]
@JonnyBGod

```
<!--
- DO NOT ask questions using GitHub issues (only bug or feature requests please,
  see http://loopback.io/doc/en/contrib/Reporting-issues.html#asking-questions)

- Please ask questions at https://groups.google.com/forum/#!forum/loopbackjs or
  https://gitter.im/strongloop/loopback

- Immediate support is available through our subscription plans, see
  https://strongloop.com/node-js/subscription-plans
-->

### Bug or feature request

- [ ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)



### Link to sample repo to reproduce issue (if bug)



### Expected result



### Actual result (if bug)



### Additional information (Node.js version, LoopBack version, etc)


```

**Comment by JonnyBGod** [comment]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

The lib should generate swagger 2 Security Definitions Object. http://swagger.io/specification/#securityDefinitionsObject

This would enable the usage of proper authentication in swagger generated documentation pages such as http://petstore.swagger.io/. (check "Authorize" button)

### Expected result

```
{
  "api_key": {
    "type": "apiKey",
    "name": "api_key",
    "in": "header"
  },
  "petstore_auth": {
    "type": "oauth2",
    "authorizationUrl": "http://swagger.io/api/oauth/dialog",
    "flow": "implicit",
    "scopes": {
      "write:pets": "modify pets in your account",
      "read:pets": "read your pets"
    }
  }
}
```

### Additional information (Node.js version, LoopBack version, etc)

**Comment by JonnyBGod** [comment]
I believe the easiest way to configure this would be to enable the developer to configure the spec in ```config.json``` and export it.

**Comment by DAVIDFlavien** [comment]
Hey there,

Is someone able to tell me if this feature is coming soon cause I need to find a way to expose my scopes required for each method in my swagger.json ? If no, do you have another way to expose the scope in the swagger.json ?

**Comment by drmikecrowe** [comment]
I have a work-in-progress that supports this (for my application).  Still needs automated tests, but the results work perfectly in http://editor.swagger.io/#!/

https://github.com/drmikecrowe/loopback-swagger

**Comment by sebastianhaas** [comment]
Still an important issue for me to be resolved.

**Comment by bajtos** [comment]
According to https://github.com/strongloop/loopback-component-explorer/pull/209#issuecomment-328522783, we need to support authorization metadata in order to be able to use the latest version of Swagger UI.

**Comment by drmikecrowe** [comment]
Continuing my OAuth2 work:

- [loopback-component-explorer](https://github.com/drmikecrowe/loopback-component-explorer)
- [loopback-swagger](https://github.com/drmikecrowe/loopback-swagger) 

I created tasks on each of what is left open (as far as I can see).  This is definitely targeting Loopback 2/3 projects, and working in an OAuth2 application we've rolled out.

**Comment by STRML** [comment]
@drmikecrowe Would you be willing to make a PR from the mergeable parts of exporting `security` and `securityDefinitions` (I see some work from @mike-zipit there in your branch) - this will help us get this throug.

**Comment by drmikecrowe** [comment]
@STRML -- Will do.  BTW, mike-zipit is my work account, so the PR will come from that fork.

**Comment by bajtos** [comment]
Closing as stale.
