### ISSUE TITLE
Some of the relation api parameters are out of sequence

### ISSUE THREAD

**Issue by taoyuan** [strongloop/loopback-swagger#67]
For `/xxxxxx/:id/yyyyyy/:fk` like api, the parameters's sequence is something like: 

```
fk:
data:
id:
```

It should show like this:

```
id:
fk:
data:
```

And also in swagger.josn generated, the order of parameters is also wrong.

**Comment by Amir-61** [comment]
Connect to https://github.com/strongloop/loopback-swagger/pull/66

Thanks for this enhancement; it seems https://github.com/strongloop/loopback-swagger/pull/66 is missing some test cases; could you please add tests, please ping me once you added, so I can get it landed.

Thanks

**Comment by taoyuan** [comment]
@Amir-61 I have added test for #66

**Comment by Amir-61** [comment]
@taoyuan Thanks for contribution! I left some minor comments; please fix them and ping me there :-)
