### ISSUE TITLE
Loopback-swagger throws Error: Invalid/unsupported swagger spec

### ISSUE THREAD

**Issue by remkohdev** [strongloop/loopback-swagger#7]
I believed this worked for me once, a few days ago, but now I cannot figure out the problem following this demo
https://github.com/strongloop/generator-loopback/tree/master/swagger

[rdeknik@oc7465160355 swagger-demo]$ node -v
v0.12.7

[rdeknik@oc7465160355 bluemix]$ slc loopback

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Let's create a LoopBack |
   `---------´   |       application!       |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What's the name of your application? swagger-demo
? Enter name of the directory to contain the project: swagger-demo
   create swagger-demo/
     info change the working directory to swagger-demo

Generating .yo-rc.json

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

   create .editorconfig
   create .jshintignore
   create .jshintrc
   create README.md
   create server/boot/authentication.js
   create server/boot/explorer.js
   create server/boot/rest-api.js
   create server/boot/root.js
   create server/middleware.json
   create server/server.js
   create .gitignore
   create client/README.md
npm WARN package.json swagger-demo@1.0.0 No license field.
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
npm WARN prefer global jshint@2.8.0 should be installed with -g
cors@2.7.1 node_modules/cors
└── vary@1.0.1

serve-favicon@2.3.0 node_modules/serve-favicon
├── fresh@0.3.0
├── etag@1.7.0
├── ms@0.7.1
└── parseurl@1.3.0

errorhandler@1.4.2 node_modules/errorhandler
├── escape-html@1.0.2
└── accepts@1.2.12 (negotiator@0.5.3, mime-types@2.1.6)

compression@1.5.2 node_modules/compression
├── bytes@2.1.0
├── vary@1.0.1
├── on-headers@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── compressible@2.0.5 (mime-db@1.18.0)
└── accepts@1.2.12 (negotiator@0.5.3, mime-types@2.1.6)

loopback-datasource-juggler@2.39.0 node_modules/loopback-datasource-juggler
├── depd@1.0.1
├── inflection@1.7.1
├── node-uuid@1.4.3
├── async@1.0.0
├── qs@3.1.0
├── debug@2.2.0 (ms@0.7.1)
├── traverse@0.6.6
└── loopback-connector@2.3.0

loopback-boot@2.12.1 node_modules/loopback-boot
├── commondir@0.0.1
├── toposort@0.2.12
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── semver@4.3.6
└── lodash@3.10.1

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0

loopback@2.22.0 node_modules/loopback
├── sl-blip@1.0.0
├── uid2@0.0.3
├── nodemailer-stub-transport@0.1.5
├── stable@0.1.5
├── canonical-json@0.0.4
├── depd@1.0.1
├── inflection@1.7.1
├── async@0.9.2
├── loopback-phase@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── loopback-connector-remote@1.0.3
├── bcryptjs@2.2.1
├── ejs@2.3.3
├── underscore.string@3.2.2
├── body-parser@1.13.3 (bytes@2.1.0, content-type@1.0.1, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.2, qs@4.0.0, type-is@1.6.8, iconv-lite@0.4.11)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, path-to-regexp@0.1.7, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, finalhandler@0.4.0, on-finished@2.3.0, qs@4.0.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.8, accepts@1.2.12)
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.6)
├── nodemailer@1.4.0 (nodemailer-direct-transport@1.0.2, nodemailer-smtp-transport@1.0.3, buildmail@1.2.4, hyperquest@1.2.0, libmime@1.0.0)
└── strong-remoting@2.20.3 (eventemitter2@0.4.14, qs@2.4.2, js2xmlparser@0.1.9, traverse@0.6.6, sse@0.0.6, mux-demux@3.7.9, request@2.61.0, jayson@1.2.1, xml2js@0.4.12)

loopback-explorer@1.8.0 node_modules/loopback-explorer
├── debug@1.0.4 (ms@0.6.2)
├── lodash@2.4.2
├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, methods@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.3.0, vary@1.0.1, basic-auth@1.0.3, range-parser@1.0.2, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, mkdirp@0.5.1, send@0.13.0, connect@2.30.2)
└── swagger-ui@2.0.24 (coffee-script@1.6.3, swagger-client@2.0.36, handlebars@1.0.12, less@1.4.2)

Next steps:

  Change directory to your app
    $ cd swagger-demo

  Create a model in your app
    $ slc loopback:model

  Compose your API, run, deploy, profile, and monitor it with Arc
    $ slc arc

  Run the app
    $ node .

[rdeknik@oc7465160355 bluemix]$ cd swagger-demo
[rdeknik@oc7465160355 swagger-demo]$ slc loopback:swagger
? Enter the swagger spec url or file path: https://raw.githubusercontent.com/reverb/swagger-spec/master/examples/v2.0/json/petstore-expanded.json
Loading https://raw.githubusercontent.com/reverb/swagger-spec/master/examples/v2.0/json/petstore-expanded.json...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Invalid/unsupported swagger spec
    at /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/swagger/spec-loader.js:111:17
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)

**Comment by bajtos** [comment]
@raymondfeng you are the author of the generator, could you PTAL?

**Comment by remkohdev** [comment]
it works for the simple petstore, but not the full petstore, btw
https://raw.githubusercontent.com/wordnik/swagger-spec/master/examples/v2.0/json/petstore-simple.json

**Comment by remkohdev** [comment]
![screenshot_error_2ndtime_simplepetstore](https://cloud.githubusercontent.com/assets/1062709/9829709/84df86ba-58de-11e5-9e1c-bdf60e0f8167.png)
The simple petstore also fails when I try to overwrite a previous run. See image, which is the error running the same simple petstore from a clean swagger-demo simple petstore twice in a row

**Comment by remkohdev** [comment]
Sorry I am blind, it only takes json, not yaml. it works with the json. apologees.
