### ISSUE TITLE
Swagger Petstore example (spec 1.2) missing store.json

### ISSUE THREAD

**Issue by wing328** [strongloop/loopback-swagger#75]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

The Swagger Petstore example (spec 1.2) seems to be broken: https://github.com/strongloop/loopback-swagger/tree/master/example/specs/1.2

It's missing `store.json` as referenced in `pet-store.json`: https://github.com/strongloop/loopback-swagger/blob/master/example/specs/1.2/pet-store.json#L14

### Link to sample repo to reproduce issue (if bug)

https://github.com/strongloop/loopback-swagger/tree/master/example/specs/1.2

### Expected result

`store.json` should not be missing

### Actual result (if bug)

`store.json` is not present in the folder: https://github.com/strongloop/loopback-swagger/tree/master/example/specs/1.2

**Comment by Amir-61** [comment]
Hey @wing328 

Thanks for bringing this to our attention; would you like to submit a patch to fix this example?

**Comment by wing328** [comment]
@Amir-61 can you please review my PR (#97) to add back the missing store.json?

**Comment by Amir-61** [comment]
@wing328 I'm not on LoopBack projects anymore... But I try to unblock it and get it landed.
