### ISSUE TITLE
Error when desactivating Explorer

### ISSUE THREAD

**Issue by microSoftware** [strongloop/loopback-swagger#80]
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Edit in component-config.json : 
```
{
  "loopback-component-explorer": null
}
```

### Expected result

Disable the /explorer

### Actual result (if bug)

And got this error when I run the server :  
```
/Applications/MAMP/htdocs/myapp/node_modules/loopback-boot/lib/config-loader.js:264
  var origValue = target[key];
                        ^

TypeError: Cannot read property 'mountPath' of null
    at mergeSingleItemOrProperty (/Applications/MAMP/htdocs/myapp/node_modules/loopback-boot/lib/config-loader.js:264:25)

```

### Additional information (Node.js version, LoopBack version, etc)
strongloop v6.0.3 (node v7.2.1)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.1 (b51fc45)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.5 (16841d6)
└── nodefly-register@0.3.3

**Comment by bajtos** [comment]
This has been fixed by https://github.com/strongloop/loopback-boot/pull/168.
