### ISSUE TITLE
From  $ref: '#/definitions/  (Swagger specification)  to  "relations": {}  (Loopback model)

### ISSUE THREAD

**Issue by Cooker-Monster** [strongloop/loopback-swagger#96]
Tricky topic I presume concerning Models Relations management shared by Swagger Spec & Loopback Model. 

It seems that relations into loopback json model are not generated by $ref declared into Swagger model when "lb swagger ...' cli is used.
 
Maybe a workaround already exists?

**Comment by raymondfeng** [comment]
@rashmihunt Can you look into this? I think we need to use [swagger-parser](https://github.com/BigstickCarpet/swagger-parser) module to load the swagger spec with `$ref` and deference such pointers to build the full spec object,
